sudo: false
dist: trusty
language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
install:
  - npm install
git:
  submodules: false
deploy:
  provider: npm
  email: development@hive.pt
  api_key:
    secure: PadffV6CfntAyCUKD+968zS8xNK1DagdChfhJOYmU8vm4nA6yo3Uj3orRQeM2j+183tPvZsOP7ZIsgClF0gPmQXpbhxbWTYRzo3J5bCP4MrKZj/OiWM2IeR4/DF0jqqnfXlKrpnq4Qrdvv8ZHx7LahzG0udJ3z6PLN4G3vfcu5wYOECM/TJ+PoOS6sUTXXI8Yw/JyI8Eb5h+JC/QdKkEv+LCpdeTdb7w1iFBe7vF7IzOyGFEuVK4x1kQjA8o36uZBYqitl7E4yzdfGhTSXZgCEkD5mNQ8VQkkFGa09EuEGdqqSfZbBasxywTN+Mv7qXFrcEB0Vjo/6jvHuT+YtXSVMC+w8ynC00G4NeRBv11CZI6DrPrgxkBRUrsU/fAmprbXaEmihHORU9ZUhJCGJtG54s0T3pgH/LsciUvxB7av8PNwsi/+BRxY+FWiakv6DBhN4d+uhBmPqYllBkU0As0ciyhy2llD6C2WtL8khqyZ7EynfcKn54xn219BPRMP/39BrNz0jHpQ/Qq0b21avxvKyQBYPxotuQI7nMSwD7AI5khSdvdyt2WTZ1ojRFPin9rFlsT/8clOFCEQMpfAUgi9yVzNoTflZ/bXrKgiqtIq61sM3dkS6VI+Lwd+iI/tf0h4ltuCE3P+qZgA45wJ1+Bw8hVKbg38YPp2751oLSpuTE=
  on:
    tags: true
    node_js: "7"
