sudo: false
dist: trusty
language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
install:
  - npm install
git:
  submodules: false
deploy:
  provider: npm
  email: development@hive.pt
  api_key:
    secure: oFZlWCRfbgZQAIwJ+tTt+T6YJrqEBy6H4qOlrWhk7tUDPMxgKEJKeT83mwEEE8rZksJkH7XqbOCMAMK749uIHyGrIOYhErc5fQP3xzLoaeDat3KNGU/7lsAfpxiYLwTnZbKVfeEOdYNd0baAqjHBY2w9Jtq5Qpa7mM06aZzA5rjKDPL4nb3GH1fgNQnig8H6vMxghssgyuXXxuxKn1P86j/C2sQtYiEZG+PaUV4j8Oba5bz38ZoA8Yz2gB2xONf9twGJeKChphsB/Ku7SddLkS2AAlQqFrF1ONRuamxn1mnRS7DcOvtiMmg5NoU7yXvFwX3qGkHCklrsq0R62DEHWY7vBxEcITlrkmpYndq2112OjKTajeGGeepVtxEgeB70lmoe7jN8p6fZg4WkssJfYPXNIoWaO7dFZGWT80eVvI4V4nIPpaWjrnvQAnrfFNkxTOR+f/8z9L5kkqrYIfKJHiPim3Dovm7sjAOlsmaFrfJf9SDKjIibPOzVOiknQoKD9aHZWYaFrm5tXYRRrzEWDeIrtcUXRzXfDnJtz8e05V6ioaVM0HVjwuWiRDf5KAUa4L0ERaE6G9l1pzHSbfY1Hy+4DFcpRD+yQyLkCFKouOn3v+gh7bMK4F4lalIJEF/rS51/+S9CztEylND0ZKw2S5xRs1VtsBBPx4vZvkA/jkw=
  on:
    tags: true
    node_js: "7"
